### ISSUE TITLE
Multi-Nav: groups become stuck in a group

### ISSUE THREAD

**Issue by rayanth** [sacada/LOGistICAL#65]
## Summary

If you have a group of trucks selected, with at least one having Multi-nav turned on, and cancel out of setting up multi-nav points, then the group will become 'stuck together' and continue to operate as a group even if only one is selected.

## Game Version

Version: LOGistICAL Earth, 853u & 853w

## Reproduction Steps

* Multi-select at least two vehicles. Ensure one has multi-nav gizmo, turned on.
* from the truck with multi-nav, start dragging a resource to go into multi-nav's selection mode.
* without selecting any destinations, hit 'done' (to 'cancel out' of multi-nav)
* turn off the multi-nav, and deselect the group.
* send one truck from the prior group to any destination, with or without cargo.
* observe that all trucks that were in the group follow. (if a resource was selected, they all will pick it up and deliver, etc)

## Expected Behaviour (optional)

Trucks that were previously in group should not continue functioning as a group when the group is no longer selected, and the trucks don't have multi-nav routes in memory.

WORKAROUND:

To 'break up' the group again:
* Multi-select the group
* turn on multi-nav
* Plot a multi-nav route of at least two destinations (just one might be sufficient)
* Click Done
* allow the trucks to finish the route
* send the trucks to some location to 'dump' any remaining cargo
* deselect the group
* they are now 'broken up' properly.

**Comment by sacada** [comment]
Fixed in build #854

**Comment by valerius31** [comment]
On build #854(openbeta) the bug still appears.
It can also be induced by the following steps.

- Multi-select at least two vehicles with multi-nav turned on
- Start dragging a resource to go into multi-nav's selection mode.
- Plot a long course that will not be completed
- When the vehicles stop, turn off multi-nav and move one of the vehicles

**Comment by rayanth** [comment]
Reportedly fixed in 854d, not yet verified.

**Comment by rayanth** [comment]
as of 855k, I haven't tried to reproduce this again, but there have been no new reports of it happening, so closing.
